import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Header from "@/components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Aditya Plastics",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header/>
        {children}
        <Toaster position="top-right" reverseOrder={false}  toastOptions={{
        duration: 7000, // 7 seconds
        style: {
          fontSize: '18px', // Increase size of the toast text
          padding: '16px',  // Increase padding for larger toast
        },
      }} />
      </body>
    </html>
  );
}
